/**
 * Server-side data fetchers for the projects feature.
 *
 * Uses createClient() from lib/supabase/server.ts (request-scoped cookie-bound
 * client) for owner-read of drafts, and publicClient from lib/supabase/public.ts
 * for the anonymous public feed where no session cookie is needed.
 *
 * NOTE: The `projects`, `project_images`, and `project_recipes` tables are not yet
 * reflected in database.types.ts — that file is regenerated by `pnpm db:types` after
 * migrations are pushed. Until then, supabase client calls use `as any` casts to
 * satisfy TypeScript; the shapes are validated at runtime via the explicit return types.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

import { createClient } from "@/lib/supabase/server";
import { isPublicSupabaseConfigured, publicClient } from "@/lib/supabase/public";
import type {
  Project,
  ProjectImage,
  ProjectListItem,
  ProjectRecipeLinkWithTitle,
  ProjectWithDetail,
} from "./types";

// ─── Project detail ───────────────────────────────────────────────────────────

/**
 * Fetch a single project by slug with its ordered images and recipe links.
 * RLS: published projects are visible to all; drafts are visible only to their author.
 */
export async function getProjectBySlug(slug: string): Promise<ProjectWithDetail | null> {
  const supabase = await createClient();

  const { data: projectRow, error: projectError } = await (supabase as any)
    .from("projects")
    .select("*")
    .eq("slug", slug)
    .maybeSingle();

  if (projectError || !projectRow) return null;

  const project = projectRow as unknown as Project;

  const [imagesResult, recipesResult] = await Promise.all([
    (supabase as any)
      .from("project_images")
      .select("id, storage_path, image_url, sort_order")
      .eq("project_id", project.id)
      .order("sort_order"),
    (supabase as any)
      .from("project_recipes")
      .select(
        "id, project_id, recipe_id, area, sort_order, note, created_at, updated_at, recipe:recipes!project_recipes_recipe_id_fkey(id, title)",
      )
      .eq("project_id", project.id)
      .order("sort_order"),
  ]);

  return {
    ...project,
    images: (imagesResult.data ?? []) as unknown as ProjectImage[],
    // Filter out links whose joined recipe is null — this happens when RLS blocks
    // an anon user from reading a private recipe that's been linked to the project.
    recipes: ((recipesResult.data ?? []) as any[]).filter(
      (r) => r.recipe !== null,
    ) as unknown as ProjectRecipeLinkWithTitle[],
  };
}

// ─── Public project feed ──────────────────────────────────────────────────────

/**
 * List all published projects, most-recently-published first.
 * Uses the public (anon-key) client so this can run in anonymous SSR contexts.
 */
export async function listPublishedProjects(): Promise<ProjectListItem[]> {
  if (!isPublicSupabaseConfigured()) return [];
  const { data, error } = await (publicClient as any)
    .from("projects")
    .select(
      `id, title, slug, summary, status, game, faction, published_at,
       cover:project_images(image_url, sort_order)`,
    )
    .eq("status", "published")
    .order("published_at", { ascending: false });

  if (error) throw new Error(`listPublishedProjects: ${error.message}`);

  return toProjectListItems(data ?? []);
}

// ─── Admin project list ───────────────────────────────────────────────────────

/**
 * List all projects belonging to the current user (admin), both draft and
 * published. Returns most-recently-updated first.
 */
export async function listAdminProjects(): Promise<ProjectListItem[]> {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return [];

  const { data, error } = await (supabase as any)
    .from("projects")
    .select(
      `id, title, slug, summary, status, game, faction, published_at,
       cover:project_images(image_url, sort_order)`,
    )
    .eq("author_user_id", user.id)
    .order("updated_at", { ascending: false });

  if (error) return [];

  return toProjectListItems(data ?? []);
}

// ─── Internal helpers ─────────────────────────────────────────────────────────

function toProjectListItems(rows: any[]): ProjectListItem[] {
  return rows.map((r) => {
    const images = (r.cover as { image_url: string; sort_order: number }[] | null) ?? [];
    const cover = images.sort((a, b) => a.sort_order - b.sort_order)[0] ?? null;
    return {
      id: r.id as string,
      title: r.title as string,
      slug: r.slug as string,
      summary: (r.summary as string | null) ?? null,
      status: r.status as ProjectListItem["status"],
      game: (r.game as string | null) ?? null,
      faction: (r.faction as string | null) ?? null,
      cover_image_url: cover?.image_url ?? null,
      published_at: (r.published_at as string | null) ?? null,
    };
  });
}
