export type PileState = "unbuilt" | "built" | "primed" | "in_progress" | "painted";

/** Client-relevant subset of the miniature_items DB row. */
export interface PileItem {
  id: string; // crypto.randomUUID() for local items; DB uuid on sync
  kit_id: string | null;
  display_name: string;
  game: string | null;
  faction: string | null;
  unit_size: number; // always 1 in this client; batch = multiple rows
  state: PileState;
  point_value: number | null;
  created_at: string; // ISO string
  painted_at: string | null; // set ONLY on the hop into "painted"
  updated_at: string; // ISO string
}

/**
 * Input shape for creating a new item. Everything optional except display_name;
 * id/created_at/updated_at are generated by the store.
 */
export type NewPileItem = Partial<Omit<PileItem, "id" | "created_at" | "updated_at">> &
  Pick<PileItem, "display_name">;

/**
 * The abstraction both localPileStore and the future supabasePileStore implement.
 * Async throughout so the Supabase backend shares the same interface without changes.
 */
export interface PileStore {
  list(): Promise<PileItem[]>;
  add(item: NewPileItem): Promise<PileItem>;
  addMany(items: NewPileItem[]): Promise<PileItem[]>;
  /** Advance to `to` (skip) or one step forward (default). Returns null if id not found. */
  advanceState(id: string, to?: PileState): Promise<PileItem | null>;
  remove(id: string): Promise<void>;
}
